### ISSUE TITLE
Updated data

### ISSUE THREAD

**Issue by dwcoder** [ImperialCollegeLondon/covid19model#108]
Would it be possible to push the newest `/data/COVID-19-up-to-date.csv` to the repository?

**Comment by verretor** [comment]
It would make more sense to provide a means to collect the data ourselves such as a scraper. Data should be in .gitignore instead of providing 18MB outdated files.

For instance, [1](https://github.com/ImperialCollegeLondon/covid19model/blob/master/Brazil/data/Global-Mobility-Report.csv) and [2](https://github.com/ImperialCollegeLondon/covid19model/blob/master/Italy/data/Global_Mobility_Report.csv) are the same file except one is older than the other.

**Comment by s-mishra** [comment]
Please look at files in data folder https://github.com/ImperialCollegeLondon/covid19model/blame/master/data/fetch-ecdc.r

It lets you update the data by yourself. Idea of giving data is ppl can match exact results we have in report/publication.
