### ISSUE TITLE
Static/Dynamic Website 

### ISSUE THREAD

**Issue by harrisonzhu508** [ImperialCollegeLondon/covid19model#11]
We should create a visualisation tool as part of the modelling that can be part of the CI/CD pipeline. Let us know below what features you would like to include! :) It could follow the lines of https://covid19uk.live/

**Comment by dentarthur** [comment]
I've put some extensive notes out of the way, here:
https://github.com/thecapitalistcycle/covid19model/issues/2

Sorry, no time to make short and clear.

**Comment by ettieunwin** [comment]
@jjminton - here is the discussion on user interfaces

**Comment by harrisonzhu508** [comment]
I think the idea here is that anything we produce here would be simple demonstrations of what we produce through our model iterations, not sophisticated webapps.

**Comment by JJMinton** [comment]
If it just presenting results then committing (compressed) results that are read and served as a static front-end with github pages would be easy.
There are dozens of options for producing the front-end; notebooks rendered to html should be easy and they support R. I don't know any R libraries that do interactive plotting but there are a few in python so I assume they exist in R.

If you're expecting this might go viral you can setup the domain with cloud-flare to handle larger traffic loads, but I'd expect github pages to be fairly robust anyway.

**Comment by s-mishra** [comment]
Thanks a lot @JJMinton  this sounds like what we should do as the first stage. Essentially static pages with clickable links for countries and sections.

**Comment by fvalka** [comment]
Hi! 

I can help with this if you like. 

I would set up a Google Cloud Platform server which does the model run and exports it to Google Cloud Storage, which is then served as a static website. As long as it remains static, that pretty much scales at Google scale, without any issues but is still pretty simple. 

For the simple version I would just do the model run, have a menu for selecting the country and then show the three panel plots and forecast for the country, as they are now. 

Anyone else working on anything concrete yet?

**Comment by harrisonzhu508** [comment]
@fvalka ThunderMikey has built a CI pipeline already with GitHub pages

**Comment by flaxter** [comment]
Just to say we currently have credits on Azure and AWS, but not Google--is
what you described easy in those environments? (Though staying entirely
within GitHub sounds good to me, if possible--github.io?)

**Comment by harrisonzhu508** [comment]
@flaxter  I think GitHub pages would probably suffice since a static site is all we need to display live results that reflect any code changes. The domain will be ImperialCollegeLondon.github.io/covid19model when it's deployed I think.

**Comment by fvalka** [comment]
@flaxter Yes, that would also work, the only limitation on AWS/S3 with regards to that which I can think of is that it's not possible to use custom domain names with HTTPS for public objects, but this isn't really an issue, as long as you don't need to host the root of the website there, so it would be possible to host only the diagrams there. 

@harrisonzhu508 @flaxter GitHub pages would also be an option, and I'm for the simplest option. The only issues I've found so far is that if you want to use the full iteration count in the sampling you would probably run out of free minutes (2000 per month), since at least for me locally the full iterations run takes about 90 minutes. Depends also if this is a paid GitHub Team account, that would have 10000 minutes per month, which would suffice if you don't have much else running in GitHub Actions, I'd say. :-) 

From what I saw it would also be possible to use GitHub actions to execute things on AWS or Azure, but I've not used that before, could also be an option, if you got credits there to outsource the model run load to Azure or AWS.

**Comment by harrisonzhu508** [comment]
@fvalka   Thanks for the suggestions. I will check with the GitHub management team at Imperial to see if we will run out of hours. I think I'd also be keen on simple solutions such as using GitHub Actions.

**Comment by fvalka** [comment]
Great! I'm right now working on extending the current R code for also exporting the plots to SVG and on a very very simple website, both of which are independent of the pipeline for feeding it :-)

**Comment by ThunderMikey** [comment]
@fvalka I was working on the static website GitHub Actions today. You might be interested in checking out [my *non-working* commits](https://github.com/ThunderMikey/covid19model). I don't have lots of time to work on this during the week. Feel free to take the lead.

**Comment by fvalka** [comment]
@ThunderMikey thanks! Sounds good. I'll especially check out your changes to the CI pipeline. I've already got the SVG export directly from the R code working though, and would go this route in order to scale the plots better for the website. I've got two different exports, for desktop and mobile, with different base_heights and aspect ratios, to keep the readability of the legend. 

I would also prefer to keep to HTML5, CSS, since I'm more familiar with those, then with transpiling markdown and will have something basic stuck together faster. 

My basic idea is to have a site where you can pick the country in a bootstrap menu, and then display the three plots from the three panel plots pdf either with the infected and deaths in the top row and the R(t) in the bottom row on desktop or below each other for mobile. Super super simple for now, and then we can see where we can/want to take it from there.

**Comment by fvalka** [comment]
And include the R(t) plot on the overview page.

**Comment by fvalka** [comment]
@harrisonzhu508 @flaxter I've made the extension to the R code for plotting the figures for the website (in mobile and desktop versions). The site itself is also ready, works on desktop, mobile and is very lightweight. I've also opened a pull-request for the changes. 

You can take a look at the proposed website on my GitHub pages:
https://fvalka.github.io/covid19model/

The missing link is still the pipeline for performing the new model runs, although the figures for the website are already being generated by the R code now, and it's just a matter of storing them and serving them.

**Comment by fvalka** [comment]
@harrisonzhu508 @s-mishra Quick update: Everything seems to work so far, I'm right now running the full model run (about 90m on my machine, don't know yet how long it'll take on GitHub) once that is finished I'll reopen a pull request :-)

**Comment by fvalka** [comment]
Ready from my perspective. See #32 

All the best, Fabian

**Comment by s-mishra** [comment]
This is currently being addressed as a new repository for website and making CI run everyday.
