### ISSUE TITLE
Where can we access the C code used to create the original report?

### ISSUE THREAD

**Issue by mrehayden1** [ImperialCollegeLondon/covid19model#46]
Where can we access the C code (referenced here: https://twitter.com/neil_ferguson/status/1241835454707699713) used in Dr Ferguson's original report ["Report 9: Impact of non-pharmaceutical interventions (NPIs) to
reduce COVID-19 mortality and healthcare demand"](https://www.imperial.ac.uk/media/imperial-college/medicine/mrc-gida/2020-03-16-COVID19-Report-9.pdf) and subsequent press briefing?

**Comment by dentarthur** [comment]
I tried to find it via refs 5 and 6 in report 9 and suspect it has not been published. Implemented by Neil Ferguson for pandemic influenza model much earlier (2006) and he would not have time now.

Here's my search results

===
From Supplementary notes to reference 5 (2006) of "Imperial College COVID-19 Response Team" model in the news right now, worldwide:

"The simulation was written in C using the OpenMP 2.0 SMP libraries. The US simulation used
some 55GB of RAM, and each realization ran in 1-2 hours on 8 CPU Opteron 854 based servers,
and in 2-5 hours on 16 CPUs of the NCSA SGI Altix 3700 system (‘cobalt’). The longer run
times on the latter system were mainly due to increased memory latency on that larger system.
Overall, approximately 20,000 CPU hours were used to generate the US results, and
approximately 8000 hours to generate the GB results."

https://static-content.springer.com/esm/art%3A10.1038%2Fnature04795/MediaObjects/41586_2006_BFnature04795_MOESM28_ESM.pdf

https://time.com/5804555/coronavirus-lockdown-uk/

https://www.imperial.ac.uk/media/imperial-college/medicine/sph/ide/gida-fellowships/Imperial-College-COVID19-NPI-modelling-16-03-2020.pdf

Reference 5 from the current model above, with direct doi link:

Ferguson, N., Cummings, D., Fraser, C. et al. Strategies for mitigating an influenza pandemic. Nature 442, 448–452 (2006).
https://doi.org/10.1038/nature04795

===

Above excerpt is from:
https://github.com/FLAMEGPU/FLAMEGPU2_dev/issues/222

Hope you can find out more! But my guess code is 14 years old and would need an independent implementation with more modern HPC GPU cluster techniques (SYCL/DPC++) from published details of model and data linked above.

**Comment by s-mishra** [comment]
Sorry, for that you need to contact Neil. It will be avaiable shortly from what I know.

**Comment by UlisseMini** [comment]
Has it been released? It has been nearly a month.

**Comment by flaxter** [comment]
If you are looking for the individual based model used in Report 9
<https://www.imperial.ac.uk/mrc-global-infectious-disease-analysis/covid-19/report-9-impact-of-npis-on-covid-19/>,
please look here <https://github.com/mrc-ide/covid-sim>
<https://github.com/ImperialCollegeLondon/covid19model#version-4-release>

**Comment by dentarthur** [comment]
Code for report 9 (and others) is linked from:
https://www.imperial.ac.uk/mrc-global-infectious-disease-analysis/covid-19/covid-19-scientific-resources/

Link is labelled as "Data"
