### ISSUE TITLE
Sweden intervention measures not in sync between current online results and PDF report

### ISSUE THREAD

**Issue by sdaume** [ImperialCollegeLondon/covid19model#64]
The PDF version of the report looking at the impact of non-pharmaceutical interventions (https://www.imperial.ac.uk/mrc-global-infectious-disease-analysis/covid-19/report-13-europe-npi-impact/) lists different interventions then the most recent online version (https://imperialcollegelondon.github.io/covid19estimates/#/details/Sweden). 
Specifically, Sweden did implement partial school closures (e.g. https://www.svt.se/nyheter/inrikes/gymnasieskolor-och-hogskolor-rekommenderas-distansundervisning) - high-schools from year 10, universities and adult education switched to distance learning from March 18th - which do not show up in the estimate shown in the most recent results up to April 14th. 
I wonder if this is intentional and how this would affect the current Rt and estimates.

P.S.: Thanks for the very informative site and for sharing the source!

**Comment by s-mishra** [comment]
Hi @sdaume , yes there is a change in interventions used but that's because of the fact we verified things again for these countries. Also, the recent results show the step you are pointing towards.
 We have both public events and social distancing in there. Yes, we have not used the partial closure as of now as it gets very difficult to get it to sync between countries. The definitions used are now directly available on the website. https://mrc-ide.github.io/covid19estimates/#/interventions
