### ISSUE TITLE
GitHub Actions

### ISSUE THREAD

**Issue by cc-a** [ImperialCollegeLondon/covid19model#9]
Following on from #4 I wanted discuss a little what should be achievable using GitHub actions to support publishing the model. At the present time I see GitHub actions as providing potentially two useful features.

1) Testing that the model **runs** on a variety of different operating systems (Linux + Windows), under different environments (Docker + Conda). This is basic validation that other people can use the model in a way that is fairly agnostic w.r.t how it is setup and run. This catches other simple to make errors such as adding a new dependency but forgetting to add it to `environment.yml` or forgetting to check in a new file with a commit.

The reason I say **runs** above is to try and emphasise the limitations of this form of testing. *This will only check that the model can be run*. It will provide no assurance about the correctness of the code or that any results produced are meaningful. It can be easy to rely too much on tests of this type but they should be considered only the most basic and crude check of a set of changes. With the attention this project has garnered you might find random PRs coming in (including from me apparently) and I don't want to give you a false sense of security about merging them. In an ideal world the project would include test code that could more robustly check incoming changes but that will have remain a manual process for now.

2) Automate the building of the Docker image and its publication for new commits to master. This saves users from having to build the Docker image themselves but also makes the model much easier to run with Docker alternatives such as [Singularity](https://sylabs.io/) that are compatible with HPC environments.

I don't think either of these is very difficult to put together. I'm sure there are all sorts of things that GitHub actions could be used for here that I've not thought so let me know if any other automatible tasks spring to mind!

Please let me know what you think. If you're interested I think a sensible way forward is for me to prototype something in my fork so you can see it in action.

**Comment by harrisonzhu508** [comment]
Hi Chris, thank you so much for your detailed suggestions.

I agree that point 1 is useful, it's always good to simply check that we can run the code!

You are absolutely right, we haven't done any unit testing yet, so that is something we should look at in the future. I think the idea of having Docker is itself very exciting, so thanks for helping us today!

I think point 2 is very useful as well, as it also promotes the open source nature of our work.

If it wouldn't take up too much of your time, it would be very beneficial for us and everyone who is interested in this work if you could have a look at these 2 features in your fork, and submit a pull request. Do let us know if you need any clarification or help at any point! Let me know and I'll close my previous PR :) 

Thanks,
Harrison

**Comment by s-mishra** [comment]
Thanks Chris, all looking forward to two additions you mentioned. They would be very useful

**Comment by cc-a** [comment]
If you point me towards the Dockerhub repository, I'll put a quick PR together updating the instructions for running with Docker.

**Comment by harrisonzhu508** [comment]
@cc-a https://hub.docker.com/repository/docker/harrisonzhu5080/covid19model here it is, thanks again.
