### ISSUE TITLE
Data for UK incorrect?

### ISSUE THREAD

**Issue by torfjelde** [ImperialCollegeLondon/covid19model#97]
Looking at https://coronavirus.data.gov.uk/ it seems like the data for daily deaths is incorrect? A quick way to check is that there are no days with > 1000 deaths in the dataset, but looking at gov-website there should be some.

Is this a mistake or are there maybe corrections to the numbers that haven't made it into the project?
Also, may I ask what your data-sources are?

Thanks!

**Comment by s-mishra** [comment]
Hi @torfjelde  our data source is ECDC. Unfortunately, yesterday they included all deaths from care/nursing homes which gave a spike. However, today ECDC has again smoothed that data to back date those deaths (to check download the file ECDC had yesterday) . So it wasn't a problem on our side but a problem on data side because of correction UK did yesterday.

**Comment by torfjelde** [comment]
Cool, I figured it was something like that :+1: Thanks!
